config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/privacy_policy', to: 'static_pages#privacy_policy'
  get  '/signup',  to: 'users#new'
  get  '/search',  to: 'static_pages#search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :videoposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  get  "users/:id/likes", to: "users#likes"
  post "likes/:videopost_id/create",  to: "likes#create"
  post "likes/:videopost_id/destroy", to: "likes#destroy"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="videoposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    フォロー
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィールを見る", user_path(current_user.id) %></span>
<span><%= pluralize(current_user.videoposts.count, "videopost") %></span>

app/views/shared/_videopost_form.html.erb
<%= form_for(@videopost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "YouTube動画のリンクを投稿してください..." %>
  </div>
  <%= f.submit "Videopostを追加！", class: "btn btn-primary" %>
<% end %>

app/views/shared/_youtube_search.html.erb
<%= form_tag search_path, method: :get do %>
  <%= text_field_tag :search, params[:keyword] %>
  <%= submit_tag 'YouTube動画を検索', class: "btn btn-primary" %>
<% end %>