config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
      }
  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/privacy_policy', to: 'static_pages#privacy_policy'
  get  '/signup',  to: 'users#new'
  get  '/search',  to: 'static_pages#search'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :videoposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  get  "users/:id/likes", to: "users#likes"
  post "likes/:videopost_id/create",  to: "likes#create"
  post "likes/:videopost_id/destroy", to: "likes#destroy"
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    ComTube
  </small>
  <nav>
    <ul>
      <li><%= link_to "ComTubeについて",   about_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
      <li><%= link_to "プライバシーポリシー", privacy_policy_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "ComTube", root_path, id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#gnavi">
          <span class="sr-only">メニュー</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div id="gnavi" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "ホーム",   root_path %></li>
          <li><%= link_to "ヘルプ",   help_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "ユーザー", users_path %></li>
            <li><%= link_to 'プロフィール変更', edit_user_registration_path %><li>
              <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %><li>
          <% else %>
            <li><%= link_to 'サインアップ', new_user_registration_path %></li>
            <li><%= link_to 'ログイン', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= analytics_init if GoogleAnalytics.valid_tracker? %>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
     <!-- FontAwesomeを読み込むlinkタグ -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>